
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Mon Oct 05 14:58:24 CDT 1998
//----------------------------------------------------

package expr;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int tDIVIDE = 5;
  static final int EOF = 0;
  static final int error = 1;
  static final int tINTCONST = 8;
  static final int tLPAREN = 6;
  static final int tRPAREN = 7;
  static final int tMINUS = 3;
  static final int tPLUS = 2;
  static final int tTIMES = 4;
}

